---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: govtech-sb-mia-aissc-vehicle-info-service
  annotations:
    backstage.io/source-location: url:https://gitlab.bcc.kz/govtech-platform/sb-mia-aissc-vehicle-info-service
    backstage.io/managed-by-location: url:https://github.com/seytzhan/govtech-backstage-catalog/blob/develop/sb-mia-aissc-vehicle-info-service/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  partOf: "domain:govtech"
  owner: govtech-clients
  system: govtech
  providesApis: [govtech-sb-mia-aissc-vehicle-info-service-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: govtech-sb-mia-aissc-vehicle-info-service-api
spec:
  type: openapi
  lifecycle: experimental
  owner: govtech-clients
  system: govtech
  definition:
    $text: https://dbp-test.bcc.kz/api/v1/gov/mia-aissc/vehicle-info/v3/api-docs