---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: govtech-sb-fl-family-info-service
  annotations:
    backstage.io/source-location: url:https://gitlab.bcc.kz/govtech-platform/sb-fl-family-info-service
    backstage.io/managed-by-location: url:https://github.com/seytzhan/govtech-backstage-catalog/blob/develop/sb-fl-family-info-service/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: govtech-clients
  system: govtech
  providesApis: [govtech-sb-fl-family-info-service-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: govtech-sb-fl-family-info-service-api
spec:
  type: openapi
  lifecycle: experimental
  owner: govtech-clients
  system: govtech
  definition:
    $text: https://dbp-dev.bcc.kz/api/v1/gov/persons-family/v3/api-docs