---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: govtech-sb-fl-service
  title: Сервис получения информации о ФЛ по ИИН
  description: Сервис предназначен для получения сведений о физических лицах по ИИН
  tags:
    - java
    - spring
  annotations:
    backstage.io/source-location: url:https://gitlab.bcc.kz/govtech-platform/sb-fl-service
    backstage.io/managed-by-location: url:https://github.com/seytzhan/govtech-backstage-catalog/blob/develop/sb-fl-service/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-id: '1639' #1234. This must be in quotes and can be found under Settings --> General
spec:
  type: service
  lifecycle: production
  partOf: "domain:govtech"
  owner: govtech-clients
  system: govtech
  providesApis: [govtech-sb-fl-service-api]
  dependsOn: []
  consumesApis: []
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: govtech-sb-fl-service-api
  title: API Сервис получения информации о ФЛ по ИИН
spec:
  type: openapi
  lifecycle: production
  owner: govtech-clients
  system: govtech
  definition:
    $text: https://dbp-test.bcc.kz/api/v1/gov/persons/v3/api-docs
