---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: govtech-client
spec:
  memberOf: [govtech-clients]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: govtech-clients
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: govtech
  description: Everything related to GovTech platform
spec:
  owner: group:govtech-clients
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: govtech
  title: Платформа Govtech
  tags:
    - java
    - spring
  links:
    - url: https://kb.apps.bcc.kz/pages/viewpage.action?pageId=160137835
      title: IAS-116413 Govtech Карточка информационной системы
      icon: cloud
spec:
  owner: govtech-clients
  domain: govtech
