---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: govtech
spec:
  owner: govtech-clients
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: govtech-sb-kdp-service
  title: Сервис контроля доступа к персональным данным
  description: Назначение сервиса - Информационная система «Контроль доступа к персональным данным», позволит обеспечить защиту персональных данных от несанкционированного доступа в государственных базах данных.
  annotations:
    backstage.io/source-location: url:https://gitlab.bcc.kz/govtech-platform/sb-kdp-service
    backstage.io/managed-by-location: url:https://github.com/seytzhan/govtech-backstage-catalog/blob/develop/sb-kdp-service/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://jira.bcc.kz/browse/GT-3242
      title: Jira Task
      icon: dashboard
  tags:
    - java
    - spring
spec:
  type: service
  lifecycle: production
  partOf: "domain:govtech"
  owner: govtech-clients
  system: govtech
  providesApis: [govtech-sb-kdp-service-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: govtech-sb-kdp-service-api
  title: API Сервис контроля доступа к персональным данным
spec:
  type: openapi
  lifecycle: production
  owner: govtech-clients
  system: govtech
  definition:
    $text: https://dbp-test.bcc.kz/api/v1/gov/person-data-access/v3/api-docs
