---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: govtech
spec:
  owner: govtech-clients
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: govtech-sb-kdp-service
  annotations:
    backstage.io/source-location: url:https://gitlab.bcc.kz/govtech-platform/sb-kdp-service
    backstage.io/managed-by-location: url:https://github.com/seytzhan/govtech-backstage-catalog/blob/develop/sb-kdp-service/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: govtech-clients
  system: govtech
  providesApis: [govtech-sb-kdp-service-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: govtech-sb-kdp-service-api
spec:
  type: openapi
  lifecycle: experimental
  owner: govtech-clients
  system: govtech
  definition:
    $text: https://dbp-test.bcc.kz/api/v1/gov/person-data-access/v3/api-docs